apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-es-http
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  clusterIP: 10.0.232.81
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127