server:
  port: 9093
spring:
  application:
    name: ${SERVICE_NAME}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/shipment_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    client-id:  ${SERVICE_NAME}
    servers: ${AXON_HOST}

pubsub:
  project-id: ${GCP_PROJECT_ID}
  topic-id: ${PUB_SUB_TOPIC_ID}
