apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: mysql-db-username
                  optional: false
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: mysql-db-userpassword
                  optional: false
          envFrom:
            - configMapRef:
                name: orderservice-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app: orderservice
  type: LoadBalancer

---

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: car-demo-order-secretstore
  namespace: default
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
      projectID: datamesh-2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: car-demo-externalsecret
  namespace: default
spec:
  secretStoreRef:
    name: car-demo-order-secretstore
    kind: SecretStore
  target:
    name: secret-to-be-created
  data:
    - secretKey: "mysql-db-username"
      remoteRef:
        key: car-demo-secret
        version: latest
        property: mysql-db-username
    - secretKey: "mysql-db-userpassword"
      remoteRef:
        key: car-demo-secret
        version: latest
        property: mysql-db-userpassword

    - secretKey: "MY_SQL_SECRETS"
      remoteRef:
        key: car-demo-secret
        version: latest

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: orderservice-configmap
data:
  # Configuration values can be set as key-value properties
  MYSQL_HOST: 34.148.245.29
  AXON_HOST: 34.74.31.122:8124
  SERVICE_NAME: OrderService
