server:
  port: 9092
spring:
  application:
    name: ${SERVICE_NAME}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/payment_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    client-id: ${SERVICE_NAME}
    servers: ${AXON_HOST}
