name: Build and Deploy to GKE

on:
  push:
    branches:
       [branch-name]
  workflow_dispatch:

env:
  IMAGE_NAME: us-central1-docker.pkg.dev/${{secrets.PROJECT_ID}}/gcp-demo-app/gcp-deployment
  PROJECT_ID: ${{secrets.PROJECT_ID}}
  GKE_CLUSTER: ${{secrets.CLUSTER_NAME}}
  GKE_ZONE: us-central1-c
  GCLOUD_AUTH: ${{secrets.GCLOUD_AUTH}}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 446.0.1'
          project_id: ${{env.PROJECT_ID}}
          service_account_key: ${{env.GCLOUD_AUTH}}
          export_default_credentials: true

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{env.GCLOUD_AUTH}}

      - name: Configure Docker for Google Cloud Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
          docker build --tag "${{ env.IMAGE_NAME }}" .
          docker push "${{ env.IMAGE_NAME }}"
  

  deploy-to-gke:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Modify YAML
        run: |
          sed -i "s#image: us-central1-docker.pkg.dev/project-id/gcp-demo-app/gcp-deployment#image: us-central1-docker.pkg.dev/${{secrets.PROJECT_ID}}/gcp-demo-app/gcp-deployment#g" k8s/deployment.yaml
      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{env.PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{env.GCLOUD_AUTH}}
          CLUSTER_NAME: ${{env.GKE_CLUSTER}}
          ZONE_NAME: ${{env.GKE_ZONE}}
        with:
          args: apply -f k8s/
