version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=mycluster
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
    networks:
      - axon-network
  mysql:
    image: mysql:8.1.0
    command: --init-file /data/application/init.sql
    restart: always
    volumes:
      - mysql-db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'

volumes:
  mysql-db:
  axonserver-data:
  axonserver-events:
  axonserver-config:

networks:
  axon-network:

# insert into products (product_id, base_price, brand, color, mileage, model, quantity,tax, timestamp,year) values('101',1000000,'Honda Car','Red',30,'JMI987',20,1.5,now(),2023);