server:
  port: 9090
spring:
  application:
    name: ${SERVICE_NAME}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/orders_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

axon:
  eventhandling:
    processors:
      order-group:
        mode: subscribing
  axonserver:
    client-id: ${SERVICE_NAME}
    servers: ${AXON_HOST}
