server:
  port: 9094
spring:
  application:
  name: ${SERVICE_NAME}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/cart_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

inventory-service:
  host: ${INVENTORY_HOST}
  product-uri: /products/product/{productId}