apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-competency-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-competency-demo
  template:
    metadata:
      labels:
        app: java-competency-demo
    spec:
      containers:
        - name: java-competency-demo
          image: ghcr.io/vimal-knoldus/az-nashtech-demo-app:${{ github.sha }}
          env:
            - name: COSMOS_KEY
              value: xRn6SPk9k0ikRWibOzsrKLul9XHBIU9RdVENhWAxgjorAWiWsmKtlIQOXcv3Dw3ryyFl0V7rrT7BACDbS9Ubzg==
            - name: COSMOS_URI
              value: https://az-nashtech-reactive-database.documents.azure.com:443/
            - name: KAFKA_SERVER
              value: az-nashtech-eventhub.servicebus.windows.net:9093
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: SASL_MECHANISM
              value: PLAIN
            - name: JASS_CONFIG
              value: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://az-nashtech-eventhub.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=K6T7DoduEzgApAedp5aBGXVmfQCLOKt3n+AEhEduFv8=";
            - name: KEY_SERIALIZER
              value: org.apache.kafka.common.serialization.StringSerializer
            - name: VALUE_SERIALIZER
              value: org.springframework.kafka.support.serializer.JsonSerializer
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-az-secret-15
